# Generated by Django 4.2.6 on 2023-10-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_age', models.IntegerField()),
                ('client_city', models.CharField(max_length=100)),
            ],
        ),
    ]
