# Generated by Django 4.2.6 on 2023-10-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_balance', models.IntegerField()),
            ],
        ),
    ]
