# Generated by Django 4.2.6 on 2023-10-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0002_client_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_payments',
            old_name='client_balance',
            new_name='client_money',
        ),
    ]
