# Generated by Django 4.2.6 on 2023-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0004_client_info_client_food_client_info_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='client_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
